DROP TABLE BOARD;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	NO NUMBER,	-- 회원번호
	ID VARCHAR2(32) NOT NULL UNIQUE,	-- 아이디
	PW VARCHAR2(32) NOT NULL,	-- 비밀번호
	NAME VARCHAR2(50),	-- 이름
	EMAIL VARCHAR2(200) NOT NULL UNIQUE,	-- 이메일
	REGDATE DATE		-- 가입일
);

CREATE TABLE BOARD(
	IDX NUMBER,		-- 게시글 번호
	AUTHOR VARCHAR2(50),	-- 작성자
	TITLE VARCHAR2(2000) NOT NULL,	-- 제목
	CONTENT VARCHAR2(4000),	-- 내용
	HIT NUMBER,	-- 조회수
	POSTDATE DATE	-- 작성일
);

ALTER TABLE MEMBER ADD CONSTAINT MEMBER_PK PRIMARY KEY(NO);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_PK PRIMARY KEY(IDX);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_MEMBER_FK FOREIGN KEY(AUTHOR) REFERENCES MEMBER(ID);

DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;